//
// CreateFeedback.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateFeedback: Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: 3, maxLength: 160, pattern: nil)
    public static let bodyRule = StringRule(minLength: 3, maxLength: 20000, pattern: nil)
    public static let turnstileTokenRule = StringRule(minLength: nil, maxLength: 2048, pattern: nil)
    public var type: FeedbackType
    /** Optional project category identifier */
    public var categoryId: String?
    public var title: String
    public var body: String
    public var priority: FeedbackPriority?
    public var email: String?
    public var platform: Platform?
    public var appVersion: String?
    public var osVersion: String?
    public var locale: String?
    public var metadata: [String: MetadataValue]?
    /** Optional short-lived Cloudflare Turnstile token; never persisted */
    public var turnstileToken: String?

    public init(type: FeedbackType, categoryId: String? = nil, title: String, body: String, priority: FeedbackPriority? = nil, email: String? = nil, platform: Platform? = nil, appVersion: String? = nil, osVersion: String? = nil, locale: String? = nil, metadata: [String: MetadataValue]? = nil, turnstileToken: String? = nil) {
        self.type = type
        self.categoryId = categoryId
        self.title = title
        self.body = body
        self.priority = priority
        self.email = email
        self.platform = platform
        self.appVersion = appVersion
        self.osVersion = osVersion
        self.locale = locale
        self.metadata = metadata
        self.turnstileToken = turnstileToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case categoryId
        case title
        case body
        case priority
        case email
        case platform
        case appVersion
        case osVersion
        case locale
        case metadata
        case turnstileToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(osVersion, forKey: .osVersion)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(turnstileToken, forKey: .turnstileToken)
    }
}

