//
// CustomField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomField: Codable, JSONEncodable, Hashable {

    public var id: String
    public var label: String
    public var type: String
    public var _required: Bool = false
    public var options: [String]

    public init(id: String, label: String, type: String, _required: Bool = false, options: [String]) {
        self.id = id
        self.label = label
        self.type = type
        self._required = _required
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case type
        case _required = "required"
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(type, forKey: .type)
        try container.encode(_required, forKey: ._required)
        try container.encode(options, forKey: .options)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CustomField: Identifiable {}
