//
// DashboardFeedbackFeedbackIdMergePostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardFeedbackFeedbackIdMergePostRequest: Codable, JSONEncodable, Hashable {

    public var targetFeedbackId: String

    public init(targetFeedbackId: String) {
        self.targetFeedbackId = targetFeedbackId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case targetFeedbackId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(targetFeedbackId, forKey: .targetFeedbackId)
    }
}

