//
// DashboardFeedbackFeedbackIdReplyPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardFeedbackFeedbackIdReplyPostRequest: Codable, JSONEncodable, Hashable {

    public static let bodyRule = StringRule(minLength: 1, maxLength: 10000, pattern: nil)
    public var body: String
    public var _internal: Bool? = false

    public init(body: String, _internal: Bool? = false) {
        self.body = body
        self._internal = _internal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case _internal = "internal"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(_internal, forKey: ._internal)
    }
}

