//
// DashboardFeedbackFeedbackIdTagsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardFeedbackFeedbackIdTagsPostRequest: Codable, JSONEncodable, Hashable {

    public var tagId: String

    public init(tagId: String) {
        self.tagId = tagId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tagId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tagId, forKey: .tagId)
    }
}

