//
// DashboardFeedbackFeedbackIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardFeedbackFeedbackIdPatchRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case complaint = "complaint"
        case bug = "bug"
        case suggestion = "suggestion"
        case featureRequest = "feature_request"
    }
    public enum Priority: String, Codable, CaseIterable {
        case low = "low"
        case normal = "normal"
        case high = "high"
        case urgent = "urgent"
    }
    public var type: ModelType?
    public var priority: Priority?
    public var categoryId: String?
    public var title: String?
    public var body: String?
    public var email: String?

    public init(type: ModelType? = nil, priority: Priority? = nil, categoryId: String? = nil, title: String? = nil, body: String? = nil, email: String? = nil) {
        self.type = type
        self.priority = priority
        self.categoryId = categoryId
        self.title = title
        self.body = body
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case priority
        case categoryId
        case title
        case body
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

