//
// DashboardProjectsProjectIdRoadmapRoadmapIdFeedbackPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdRoadmapRoadmapIdFeedbackPostRequest: Codable, JSONEncodable, Hashable {

    public var feedbackId: String

    public init(feedbackId: String) {
        self.feedbackId = feedbackId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feedbackId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feedbackId, forKey: .feedbackId)
    }
}

