//
// DashboardFeedbackFeedbackIdAssignPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardFeedbackFeedbackIdAssignPostRequest: Codable, JSONEncodable, Hashable {

    public var assigneeUserId: String?

    public init(assigneeUserId: String? = nil) {
        self.assigneeUserId = assigneeUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assigneeUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(assigneeUserId, forKey: .assigneeUserId)
    }
}

