//
// DashboardProjectsProjectIdModerationPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdModerationPostRequest: Codable, JSONEncodable, Hashable {

    public enum Outcome: String, Codable, CaseIterable {
        case approved = "approved"
        case rejected = "rejected"
        case spam = "spam"
    }
    public var feedbackId: String
    public var outcome: Outcome

    public init(feedbackId: String, outcome: Outcome) {
        self.feedbackId = feedbackId
        self.outcome = outcome
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feedbackId
        case outcome
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feedbackId, forKey: .feedbackId)
        try container.encode(outcome, forKey: .outcome)
    }
}

