//
// DashboardBillingCheckoutPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardBillingCheckoutPostRequest: Codable, JSONEncodable, Hashable {

    public enum Plan: String, Codable, CaseIterable {
        case pro = "pro"
        case business = "business"
    }
    public var plan: Plan

    public init(plan: Plan) {
        self.plan = plan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plan, forKey: .plan)
    }
}

