//
// DashboardProjectsProjectIdWebhooksPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdWebhooksPostRequest: Codable, JSONEncodable, Hashable {

    public enum Events: String, Codable, CaseIterable {
        case feedbackPeriodCreated = "feedback.created"
        case feedbackPeriodUpdated = "feedback.updated"
        case feedbackPeriodReplied = "feedback.replied"
    }
    public var url: String
    public var events: [Events]?

    public init(url: String, events: [Events]? = nil) {
        self.url = url
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

