//
// DashboardProjectsProjectIdPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdPatchRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var slug: String?

    public init(name: String? = nil, slug: String? = nil) {
        self.name = name
        self.slug = slug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case slug
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
    }
}

