//
// DashboardProjectsProjectIdNotificationsPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdNotificationsPatchRequest: Codable, JSONEncodable, Hashable {

    public enum EventType: String, Codable, CaseIterable {
        case feedbackPeriodCreated = "feedback.created"
        case feedbackPeriodUpdated = "feedback.updated"
        case feedbackPeriodReplied = "feedback.replied"
        case moderationPeriodCreated = "moderation.created"
    }
    public var eventType: EventType
    public var enabled: Bool

    public init(eventType: EventType, enabled: Bool) {
        self.eventType = eventType
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(enabled, forKey: .enabled)
    }
}

