//
// DashboardRoadmapPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardRoadmapPostRequest: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case planned = "planned"
        case inProgress = "in_progress"
        case completed = "completed"
    }
    public var title: String
    public var body: String?
    public var status: Status?

    public init(title: String, body: String? = nil, status: Status? = nil) {
        self.title = title
        self.body = body
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case body
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

