//
// DashboardChangelogPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardChangelogPostRequest: Codable, JSONEncodable, Hashable {

    public var title: String
    public var body: String
    public var publishedAt: Date?

    public init(title: String, body: String, publishedAt: Date? = nil) {
        self.title = title
        self.body = body
        self.publishedAt = publishedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case body
        case publishedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(publishedAt, forKey: .publishedAt)
    }
}

