//
// DashboardProjectsProjectIdApiKeysPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardProjectsProjectIdApiKeysPostRequest: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case _public = "public"
        case server = "server"
    }
    public var kind: Kind
    public var label: String?

    public init(kind: Kind, label: String? = nil) {
        self.kind = kind
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(label, forKey: .label)
    }
}

