//
// DeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteResponse: Codable, JSONEncodable, Hashable {

    public var deleted: Bool
    public var feedbackId: String

    public init(deleted: Bool, feedbackId: String) {
        self.deleted = deleted
        self.feedbackId = feedbackId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deleted
        case feedbackId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(feedbackId, forKey: .feedbackId)
    }
}

