//
// Feedback.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Feedback: Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: 3, maxLength: 160, pattern: nil)
    public static let bodyRule = StringRule(minLength: 3, maxLength: 20000, pattern: nil)
    public static let turnstileTokenRule = StringRule(minLength: nil, maxLength: 2048, pattern: nil)
    public var type: FeedbackType
    /** Optional project category identifier */
    public var categoryId: String?
    public var title: String
    public var body: String
    public var priority: FeedbackPriority?
    public var email: String?
    public var platform: Platform?
    public var appVersion: String?
    public var osVersion: String?
    public var locale: String?
    public var metadata: [String: MetadataValue]?
    /** Optional short-lived Cloudflare Turnstile token; never persisted */
    public var turnstileToken: String?
    public var id: UUID
    public var projectId: String
    public var status: FeedbackStatus
    public var createdAt: Date
    public var updatedAt: Date

    public init(type: FeedbackType, categoryId: String? = nil, title: String, body: String, priority: FeedbackPriority? = nil, email: String? = nil, platform: Platform? = nil, appVersion: String? = nil, osVersion: String? = nil, locale: String? = nil, metadata: [String: MetadataValue]? = nil, turnstileToken: String? = nil, id: UUID, projectId: String, status: FeedbackStatus, createdAt: Date, updatedAt: Date) {
        self.type = type
        self.categoryId = categoryId
        self.title = title
        self.body = body
        self.priority = priority
        self.email = email
        self.platform = platform
        self.appVersion = appVersion
        self.osVersion = osVersion
        self.locale = locale
        self.metadata = metadata
        self.turnstileToken = turnstileToken
        self.id = id
        self.projectId = projectId
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case categoryId
        case title
        case body
        case priority
        case email
        case platform
        case appVersion
        case osVersion
        case locale
        case metadata
        case turnstileToken
        case id
        case projectId
        case status
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encodeIfPresent(osVersion, forKey: .osVersion)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(turnstileToken, forKey: .turnstileToken)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Feedback: Identifiable {}
