//
// FeedbackType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FeedbackType: String, Codable, CaseIterable {
    case complaint = "complaint"
    case bug = "bug"
    case suggestion = "suggestion"
    case featureRequest = "feature_request"
}
