//
// FeedbackStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FeedbackStatus: String, Codable, CaseIterable {
    case new = "new"
    case triaged = "triaged"
    case planned = "planned"
    case inProgress = "in_progress"
    case resolved = "resolved"
    case closed = "closed"
    case spam = "spam"
}
