//
// FollowUpFeedback.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FollowUpFeedback: Codable, JSONEncodable, Hashable {

    public var id: String
    public var type: FeedbackType
    public var status: FeedbackStatus
    public var priority: FeedbackPriority
    public var title: String
    public var body: String
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: String, type: FeedbackType, status: FeedbackStatus, priority: FeedbackPriority, title: String, body: String, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.type = type
        self.status = status
        self.priority = priority
        self.title = title
        self.body = body
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case status
        case priority
        case title
        case body
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(status, forKey: .status)
        try container.encode(priority, forKey: .priority)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FollowUpFeedback: Identifiable {}
