//
// FollowUp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FollowUp: Codable, JSONEncodable, Hashable {

    public var feedback: FollowUpFeedback
    public var comments: [FollowUpComment]

    public init(feedback: FollowUpFeedback, comments: [FollowUpComment]) {
        self.feedback = feedback
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feedback
        case comments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feedback, forKey: .feedback)
        try container.encode(comments, forKey: .comments)
    }
}

