//
// Platform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Platform: String, Codable, CaseIterable {
    case web = "web"
    case ios = "ios"
    case android = "android"
    case other = "other"
}
