//
// ProjectsProjectIdFeedbackFeedbackIdCommentsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectsProjectIdFeedbackFeedbackIdCommentsPostRequest: Codable, JSONEncodable, Hashable {

    public static let bodyRule = StringRule(minLength: 1, maxLength: 10000, pattern: nil)
    public var body: String

    public init(body: String) {
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(body, forKey: .body)
    }
}

