//
// ProjectsProjectIdUploadsInitiatePostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectsProjectIdUploadsInitiatePostRequest: Codable, JSONEncodable, Hashable {

    public static let sizeRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var feedbackId: String?
    public var contentType: String
    public var size: Int

    public init(feedbackId: String? = nil, contentType: String, size: Int) {
        self.feedbackId = feedbackId
        self.contentType = contentType
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feedbackId
        case contentType
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(feedbackId, forKey: .feedbackId)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(size, forKey: .size)
    }
}

