//
// ProjectsProjectIdFollowUpRequestPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectsProjectIdFollowUpRequestPostRequest: Codable, JSONEncodable, Hashable {

    public var feedbackId: String
    public var email: String

    public init(feedbackId: String, email: String) {
        self.feedbackId = feedbackId
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feedbackId
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feedbackId, forKey: .feedbackId)
        try container.encode(email, forKey: .email)
    }
}

