//
// PublicTheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicTheme: Codable, JSONEncodable, Hashable {

    public var mode: String?
    public var buttonLabel: String?
    public var fields: [String]?
    public var customFields: [CustomField]?
    public var colors: [String: String]?

    public init(mode: String? = nil, buttonLabel: String? = nil, fields: [String]? = nil, customFields: [CustomField]? = nil, colors: [String: String]? = nil) {
        self.mode = mode
        self.buttonLabel = buttonLabel
        self.fields = fields
        self.customFields = customFields
        self.colors = colors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
        case buttonLabel
        case fields
        case customFields
        case colors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(buttonLabel, forKey: .buttonLabel)
        try container.encodeIfPresent(fields, forKey: .fields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(colors, forKey: .colors)
    }
}

