//
// PublicConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicConfig: Codable, JSONEncodable, Hashable {

    public var theme: PublicTheme
    public var categories: [Category]

    public init(theme: PublicTheme, categories: [Category]) {
        self.theme = theme
        self.categories = categories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case theme
        case categories
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(theme, forKey: .theme)
        try container.encode(categories, forKey: .categories)
    }
}

