//
// UploadInitiation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadInitiation: Codable, JSONEncodable, Hashable {

    public var attachmentId: String
    public var uploadUrl: String

    public init(attachmentId: String, uploadUrl: String) {
        self.attachmentId = attachmentId
        self.uploadUrl = uploadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attachmentId
        case uploadUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attachmentId, forKey: .attachmentId)
        try container.encode(uploadUrl, forKey: .uploadUrl)
    }
}

