//
// UploadsUploadTokenPut201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UploadsUploadTokenPut201Response: Codable, JSONEncodable, Hashable {

    public var attachmentId: String

    public init(attachmentId: String) {
        self.attachmentId = attachmentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attachmentId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attachmentId, forKey: .attachmentId)
    }
}

